package config

var T8Stages = map[string]string{
	"arena":                         "Arena",
	"arena (underground)":           "Arena (Underground)",
	"urban square":                  "Urban Square",
	"urban square (evening)":        "Urban Square (Evening)",
	"yakushima":                     "Yakushima",
	"coliseum of fate":              "Coliseum of Fate",
	"rebel hangar":                  "Rebel Hanger",
	"fallen destiny":                "Fallen Destiny",
	"descent into subconsciousness": "Descent into Subconsciousness",
	"sanctum":                       "Sanctum",
	"into the stratpsphere":         "Into the Stratosphere",
	"ortiz farm":                    "Ortiz Farm",
	"celebration on the seine":      "Celebration on the Seine",
	"secluded training ground":      "Secluded Training Ground",
	"elegant palace":                "Elegant Palace",
	"midnight siege":                "Midnight Siege",
	"seaside resort":                "Seaside Resort",
	"genmaji temple":                "Genmaji Temple",
	"genmaji temple (daytime)":      "Genmaji Temple (Daytime)",
}

var SF6Stages = map[string]string{
	"enmas hollow":           "Enma's Hollow",
	"ruined lab":             "Ruined Lab",
	"barmaley steelworks":    "Barmaley Steelworks",
	"bathers beach":          "Bathers Beach",
	"carrier byron taylor":   "Carrier Byron Taylor",
	"colosseo":               "Colosseo",
	"dhalsimer temple":       "Dhalsimer Temple",
	"fête foraine":           "Fête Foraine",
	"genbu temple":           "Genbu Temple",
	"king street":            "King Street",
	"metro city downtown":    "Metro City Downtown",
	"old town market":        "Old Town Market",
	"ranger's hut":           "Ranger's Hut",
	"suval'hal arena":        "Suval'hal Arena",
	"the macho ring":         "The Macho Ring",
	"thunderfoot settlement": "Thunderfoot Settlement",
	"tian hong yuan":         "Tian Hong Yuan",
	"training Room":          "Training Room",
}
